# Use root/example as user/password credentials
version: '3.8'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: test

  db2:
    image: postgres
    restart: always
    ports:
      - 3307:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test

  db3:
    image: mysql
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test